const DROP_TEAM = 'DROP TABLE IF EXISTS Team;';
const DROP_SPONSORS = 'DROP TABLE IF EXISTS Sponsors'; 
const DROP_HELPS = 'DROP TABLE IF EXISTS Helps'; 
const DROP_STAFF = 'DROP TABLE IF EXISTS Staff'; 
const DROP_SUPPORTS = 'DROP TABLE IF EXISTS Supports'; 
const DROP_PLAYERS = 'DROP TABLE IF EXISTS Players'; 
const DROP_PLAYER_HAS_STATS = 'DROP TABLE IF EXISTS Player_Has_Statistics'; 
const DROP_PLAYER_ENDORSEMENTS_CONTRACTS = 'DROP TABLE IF EXISTS Player_Endorsement_Contracts'; 
const DROP_PLAYS_FOR = 'DROP TABLE IF EXISTS Plays_For'; 
const DROP_PLAYER_CONTRACT_DURATION = 'DROP TABLE IF EXISTS Player_Contract_Duration'; 
const DROP_ROSTER = 'DROP TABLE IF EXISTS Rosters'; 
const DROP_COACHES = 'DROP TABLE IF EXISTS Coaches'; 
const DROP_COACH_CONTRACT_DURATION = 'DROP TABLE IF EXISTS Coach_Contract_Duration'; 
const DROP_HAS = 'DROP TABLE IF EXISTS HAS';
const DROP_COACH = 'DROP TABLE IF EXISTS Coach'

module.exports = {DROP_COACH, DROP_TEAM, DROP_SPONSORS, DROP_HAS, DROP_HELPS, DROP_STAFF, DROP_SUPPORTS, DROP_PLAYERS, DROP_PLAYER_HAS_STATS, DROP_PLAYER_ENDORSEMENTS_CONTRACTS, DROP_PLAYS_FOR, DROP_PLAYER_CONTRACT_DURATION, DROP_ROSTER, DROP_COACHES, DROP_COACH_CONTRACT_DURATION};